/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-101261-g78d5e1c653-QtAV"
#endif /* AVUTIL_FFVERSION_H */
